name: action
usage: command {args...}
description: Makes many interesting things
sources:
  - file://example/actions
  - http://127.0.0.1:3000/api/v1.0/crackcomm/action-app/actions/
commands:
  -
    name: movie
    usage: "{title}"
    action: filmweb.find
    example: pulp fiction
    description: Finds movie on filmweb.pl
    arguments:
      -
        name: title
        required: true
        push: query.q
    flags:
      -
        name: title
        required: true
        push: query.q
        description: movie title
  -
    name: music
    usage: "{title}"
    action: youtube.find
    example: 2pac
    description: Finds music on youtube.com
    arguments:
      -
        name: title
        required: true
        push: query.search_query
  -
    name: get
    action: http.get
    example: http://google.com
    description: Requests HTTP url and prints response
    arguments:
      -
        name: url
        required: true
